# This file was auto-generated by salt's setup on Thursday, 20 August 2015 @ 17:08:02 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 5, 5, 0, 0, 0, None)
